l_separator = ""
r_separator = ""

[[l_components_first]]
name = "Id"
color = "Magenta"

[[l_components_first]]
name = "Dir"
color = "Blue"

[[l_components_first]]
name = "GitName"
color = "Yellow"

[[l_components_first]]
name = "GitCurrentBranchAndStatuses"
color = "Green"

[[l_components_first]]
name = "GitStash"
color = "White"

[[l_components_first]]
name = "GitRemotesAndStatuses"
color = "Cyan"

[[l_components_second]]
name = "DateTime"
color = "White"
date_time_format = "+%m/%d %H:%M:%S"
ng_color = "Red"

[[l_components2]]
name = "None"
color = "White"
ng_color = "Red"
